name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare (Main)
        uses: ynufes-tech/reusable-actions/.github/actions/cf-worker-deploy@main
        with:
          worker_name: "ynufes-seiryo22"
          wrangler_template: "wrangler.template.toml"
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
